# please rename to "config.yaml"

gyazz : "gyazz-name"
3memo : "3memo-name"

# gyazz_user : 'http-basic-user'
# gyazz_pass : 'http-basic-pass'

im_kayac_users : # im.kayac.com usernames
 - "user1"
 - "user2"


# twitter config
consumer_key : 'your-app-consumer-key'
consumer_secret : 'your-app-consumer-secret'
access_token : 'use auth.rb'
access_secret : 'use auth.rb'

# no_tweet : "true"
