# please rename to "config.yaml"

gyazz : "gyazz-name"
3memo : "3memo-name"

im_kayac_users : # im.kayac.com usernames
 - "user1"
 - "user2"

twitter_user : "your-twitter-account"
twitter_pass : "your-twitter-passwd"
# no_tweet : "true"
